services:
  url-shortener:
    build:
      context: .
      dockerfile: docker/url-shortener/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - redis

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"